alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student_phoneNumbers drop constraint FKcw90n87pnmj6u2f5njkcg779l
drop table if exists Address cascade
drop table if exists Student cascade
drop table if exists Student_phoneNumbers cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
alter table Student drop constraint FKt6gnpaxnx9cm4x1os2t936fsm
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Phone cascade
drop table if exists Student cascade
